# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161117_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='unique_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
