# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161117_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundBeacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('lat', models.CharField(blank=True, max_length=30, null=True)),
                ('long', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(null=True)),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Beacon')),
            ],
        ),
        migrations.CreateModel(
            name='LostBeacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lat', models.CharField(blank=True, max_length=30, null=True)),
                ('long', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(null=True)),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Beacon')),
            ],
        ),
    ]
