# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostbeacon',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
