# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_foundbeacon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundbeacon',
            name='distance',
            field=models.FloatField(null=True),
        ),
    ]
