# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_foundbeacon_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
