# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_beacon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundbeacon',
            name='reward',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lostbeacon',
            name='reward',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
